name: MineUtils
version: '${version}'

main: com.wsdev.mineUtils.MineUtils
api-version: '26.1.2'
load: POSTWORLD

commands:
  feed:
    description: "Restaura a fome do jogador."
    usage: /feed

  health:
    description: "Restaura a vida do jogador"
    usage: /health

  report:
    description: "Utilizado para denunciar um jogador"
    usage: /report <jogador> <motivo>